config/routes.rb
Rails.application.routes.draw do
  devise_for :membros, controllers: { omniauth_callbacks: 'membros/omniauth_callbacks' }
  resources :eventos
  resources :membros
  resources :inscricaos
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/membro.rb
class Membro < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_one_attached :rosto
end

app/controllers/membros/omniauth_callbacks_controller.rb
class Membros::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/membro.rb)
        @Membro = Membro.from_omniauth(request.env['omniauth.auth'])
  
        if @membro.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @membro, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_membro_registration_url, alert: @membro.errors.full_messages.join("\n")
        end
    end
    def self.from_omniauth(access_token)
        data = access_token.info
        membro = membro.where(email: data['email']).first
    
        # Uncomment the section below if you want membros to be created if they don't exist
        unless membro
            membro = membro.create(name: data['name'],
            email: data['email'],
            password: Devise.friendly_token[0,20]
            )
        end

        membro
    end
  end

app/controllers/membros_controller.rb
class MembrosController < ApplicationController
  before_action :set_membro, only: %i[ show edit update destroy ]
  before_action :authenticate_membro!, :except => [:index, :show]

  # GET /membros or /membros.json
  def index
    @membros = Membro.all
  end

  # GET /membros/1 or /membros/1.json
  def show
  end

  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros or /membros.json
  def create
    @membro = Membro.new(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to membro_url(@membro), notice: "Membro was successfully created." }
        format.json { render :show, status: :created, location: @membro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membros/1 or /membros/1.json
  def update
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to membro_url(@membro), notice: "Membro was successfully updated." }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membros/1 or /membros/1.json
  def destroy
    @membro.destroy!

    respond_to do |format|
      format.html { redirect_to membros_url, notice: "Membro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro
      @membro = Membro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membro_params
      params.require(:membro).permit(:nome, :etapa, :rosto, :rg, :celular, :anoDeInscricao, :localEcyd, :restricao)
    end
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/views/membros/_eventos.html.erb
<% @inscritos = Inscricao.where(membro_id: @membro.id) %>
    <% @inscritos.each do |inscrito| %>
      <% if inscrito.evento %>
        <%= inscrito.evento.titulo %>
      <% else %>
        <p> [REMOVIDO] </p>
      <% end %>
      <br/>
<% end %>

app/views/membros/_form.html.erb
<%= form_with(model: membro, class: "contents") do |form| %>
  <% if membro.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(membro.errors.count, "error") %> prohibited this membro from being saved:</h2>

      <ul>
        <% membro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :etapa %>
    <%= form.text_field :etapa, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rosto %>
    <%= form.file_field :rosto, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "rG" %>
    <%= form.number_field :rg, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :celular %>
    <%= form.number_field :celular, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Ano de Inscrição" %>
    <%= form.number_field :anoDeInscricao, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% items = [{:value => "1", name: "Everest Lago Sul"}, {:value => "2", name: "Guadalupe"}, {:value => "3", name: "Forzza"}, {:value => "4", name: "Everest Asa Norte"}] %>
    <%= form.label "Local de ECyD" %>
    <%#= form.number_field :localEcyd, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <%= render_combobox items do %>
    <%= combobox_trigger do %>
      Selecione o Local de ECyD
    <% end %>
  <% end %>
  
  </div>

  <div class="my-5">
    <%= form.label "Restrição Alimentar" %>
    <%= form.text_field :restricao, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>OS CAMPOS A SEGUIR SÃO SOMENTE PARA O AMBIENTE DE TESTES</div>
  <div class="my-5">
    <%= form.label "Email" %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Enviar",  class: "rounded-lg py-3 px-5 bg-RC-dark text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/membros/_membro-detalhes.html.erb
<div id="<%= dom_id membro %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= membro.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Etapa:</strong>
    <%= membro.etapa %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rosto:</strong>
    <% if membro.rosto? %>
      <%= image_tag(membro.rosto) %>
    <% end %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">RG:</strong>
    <%= membro.rg %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Celular:</strong>
    <%= membro.celular %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ano de Inscrição:</strong>
    <%= membro.anoDeInscricao %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Local de ECyD:</strong>
    <%= membro.localEcyd %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Restrição Alimentar:</strong>
    <%= membro.restricao %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= membro.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Eventos:</strong>
    <%= render "eventos", membro: @membro %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Mais Informações", membro, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Editar", edit_membro_path(membro), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/membros/_membro.html.erb
<div id="id" class="my-5">
  <%= render_card(title: membro.nome, subtitle: "Etapa: " + membro.etapa) do %>
          <%= link_to "Mais Informações", membro, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          <%= link_to "Editar", edit_membro_path(membro), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
  <% end %>
</div>

app/views/membros/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Complete seu cadastro:</h1>

  <%= render "form", membro: @membro %>

  <%= link_to "Mais Informações", @membro, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Voltar", membros_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/membros/index.html.erb
<div class="w-full"> 
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Membros</h1>
    <%= link_to "Novo membro", new_membro_path, class: "rounded-lg py-3 px-5 bg-RC-dark text-white block font-medium" %>
  </div>

  <div id="membros" class="min-w-full">
    <%= render @membros %>
  </div>
  
  <% if notice.present? %> 
    <%= render_toast header: notice %>
  <% end %>
</div>

app/views/membros/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New membro</h1>

  <%= render "form", membro: @membro %>

  <%= link_to "Voltar", membros_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/membros/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <%= render_toast header: notice %>
    <% end %>

    <%= render "membro-detalhes", membro: @membro %>

    <%= link_to "Editar", edit_membro_path(@membro), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Remover", membro_path(@membro), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Voltar", membros_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>