config/routes.rb
Rails.application.routes.draw do
  devise_for :membros, controllers: { omniauth_callbacks: 'membros/omniauth_callbacks' }
  resources :eventos
  resources :membros
  resources :inscricaos
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/evento.rb
class Evento < ApplicationRecord
    has_many :membros
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: %i[ show edit update destroy ]

  # GET /eventos or /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1 or /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos or /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to evento_url(@evento), notice: "Evento was successfully created." }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1 or /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to evento_url(@evento), notice: "Evento was successfully updated." }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1 or /eventos/1.json
  def destroy
    @evento.destroy!

    respond_to do |format|
      format.html { redirect_to eventos_url, notice: "Evento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evento_params
      params.require(:evento).permit(:titulo, :descricao, :data, :local, :inscritos)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_evento-detalhes.html.erb
<div id="<%= dom_id evento %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Titulo:</strong>
    <%= evento.titulo %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Descricao:</strong>
    <%= evento.descricao %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Data:</strong>
    <%= evento.data %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Local:</strong>
    <%= evento.local %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Inscritos:</strong>
    <%= render "inscritos", evento: @evento%>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this evento", evento, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this evento", edit_evento_path(evento), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/eventos/_evento.html.erb
<div id="<%= dom_id evento %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Titulo:</strong>
    <%= evento.titulo %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Data:</strong>
    <%= evento.data %>
  </p>


  <% if action_name != "show" %>
    <%= link_to "Detalhes", evento, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Editar", edit_evento_path(evento), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/eventos/_form.html.erb
<%= form_with(model: evento, class: "contents") do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(evento.errors.count, "error") %> causou a falha na criação do evento:</h2>

      <ul>
        <% evento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Descrição" %>
    <%= form.text_area :descricao, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :data %>
    <%= form.date_field :data, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :local %>
    <%= form.text_field :local, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-RC-dark text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/eventos/_inscricao.html.erb
<%= form_for Inscricao.new do |f| %>
      <%= f.hidden_field :membro_id, value: @membro.id %>
      <%= f.hidden_field :evento_id, value: @evento.id %>

      <%= f.submit %>
<% end %>

app/views/eventos/_inscritos.html.erb
<% @inscritos = Inscricao.all %>
    <% @inscritos.each do |inscrito| %>
      <% if inscrito.membro %>
        <%= inscrito.membro.nome %>
      <% else %>
        <p> [REMOVIDO] </p>
      <% end %>
      <br/>
    <% end %>
<%= evento.inscritos %>

app/views/eventos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing evento</h1>

  <%= render "form", evento: @evento %>

  

  <%= link_to "Mostrar esse Evento", @evento, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium bg-RC-light" %>
  <%= link_to "Voltar aos Eventos", eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/eventos/index.html.erb
<div class="w-full">
  <% if notice.present? %> 
    <%= render_toast header: notice %>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Eventos</h1>
    <%= link_to "New evento", new_evento_path, class: "rounded-lg py-3 px-5 bg-RC-dark text-white block font-medium" %>
  </div>

  <div id="eventos" class="min-w-full">
    <%= render @eventos %>
  </div>
</div>

app/views/eventos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New evento</h1>

  <%= render "form", evento: @evento %>

  <%= link_to "Back to eventos", eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-RC-light inline-block font-medium" %>
</div>

app/views/eventos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <% @membro = current_membro %>

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "evento-detalhes", evento: @evento %>

    

    <%= render "inscricao", membro: @membro, evento: @evento %>

    <%= link_to "Editar", edit_evento_path(@evento), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Deletar esse Evento", evento_path(@evento), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Voltar para eventos", eventos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>